site_name: 'MicroPython'
nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Micropython Home: index.md
  - Getting Started:
    - Introduction: getting-started/01-intro.md
    - Microcontrollers: getting-started/01a-microcontrollers.md
    - Boards: getting-started/02-boards.md
    - Displays: getting-started/10-displays.md
    - Sourcing Parts: getting-started/03-suggested-parts.md
    - Raspberry Pi Pico: getting-started/02-pi-pico.md
    - ESP32: getting-started/02-esp32.md
    - Thonny IDE: getting-started/02c-thonny.md
    - VS Code IED: getting-started/02d-vscode.md
    - MicroPython Libraries: getting-started/01b-libraries.md
  - Basic Examples:
    - Introduction: intro/01-intro.md
    - Blink: intro/03-blink.md
    - Buttons: intro/03-button.md
    - Temperature: intro/03-temperature.md
    - Motor: intro/04-motor.md
    - Servo: intro/04-servo.md
    - LED Strip: intro/05-led-strip.md
    - Displays: intro/10-displays.md
    - Character LCD: intro/10-character-lcd-display.md
  - Sensors:
    - Introduction: sensors/01-intro.md
    - Photosensor: sensors/02-photosensor.md
    - Ping Distance: sensors/03-ping.md
    - Temp,Humidity, Pres: sensors/06-bme280.md
    - Potentiometer: sensors/02-pot.md
    - Environmental Sensor: sensors/bme280.md
    - Accelerometer Compass: sensors/06-accelerometer-compass.md
    - Time of Flight Distance: sensors/07-VL53L0X_GY.md
  - Displays:
    - 7 Segment Display: displays/7-segment-display.md
  - OLED Displays:
    - Introduction: oled/01-oled-intro.md
    - Setup: oled/02-oled-setup.md
    - Drawing: oled/03-oled-drawing.md
    - OLED SSD1306 I2C: oled/11-oled-ssd1306-i2c.md
    - OLED SSD1306 SPI V1: oled/12-oled-ssd1306-spi-v1.md
    - OLED SSD1306 SPI V2: oled/11-oled-ssd1306-spi.md
    - OLED SH1106 I2C Example: oled/11-oled-sh1106-i2c.md
    - OLED Bounce: oled/10-oled-bounce.md
    - OLED Pot: oled/12-oled-pot.md
    - OLED Ping: oled/11-oled-ping.md
    - OLED Pong: oled/11-pong.md
    - OLED Pixel Draw: oled/13-pixel-draw.md
    - OLED Patterns: oled/15-oled-patterns.md
    - Random Hearts: oled/14-random-hearts.md
    - OLED References: oled/40-oled-references.md
  - Sound and Music:
    - Introduction: sound/01-intro.md
    - Playing a Tone: sound/02-play-tone.md
    - Playing Three Tones: sound/03-play-three-tones.md
    - Playing a Scale: sound/04-play-scale.md
    - Play Mario: sound/05-play-mario.md
  - Pico Robots:
    - Introduction: robots/01-intro.md
    - Base Bot: robots/02-base-bot.md
    - Rainbow Bot: robots/03-rainbow-bot.md
    - Face Bot: robots/03-face-bot.md
    - Param Bot: robots/04-param-bot.md
    - Servo Bot: robots/05-servo-bot.md
    - IR Sensor Bot: 03-ir-collision-avoidance-sensor.md
    - FAQs: robots/20-faqs.md
  - Debugging:
    - Debugging Python: debugging/28-debugging-python.md
    - Debugging I2C: debugging/29a-debugging-i2c.md
    - Debugging SPI: debugging/29-debugging-spi.md
    - Ampy: debugging/27-ampy.md
    - Content Outliner: debugging/40-gpt-outliner.md
  - Circuit Python:
    - circuit-python/01-intro.md
  - Projects: misc/projects.md
  - Glossary: misc/glossary.md
  - References: misc/references.md
  - Contributing: misc/contributing.md
  - Contact: misc/contact.md
  - Colophon: misc/30-colophon.md
  - Render Test: misc/mermaid-test.md

site_description: 'Resources for teaching Micropython to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'micropython repo'
repo_url: 'https://github.com/CoderDojoTC/micropython'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - search
  # - mermaid2
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences