site_name: 'MicroPython'
nav:
  - CoderDojo Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Micropython Home: index.md
  - Getting Started:
    - Introduction: 01-intro.md
    - Microcontrollers: 01a-microcontrollers.md
    - Boards: 02-boards.md
    - Accessories: 02b-accessories.md
    - Raspberry Pi Pico: 02-pi-pico.md
    - ESP32: 02-esp32.md
    - Thonny IDE: 02c-thonny.md
    - Python Libraries: 01b-libraries.md
  - MicroPython Examples:
    - Blink: 03-blink.md
    - Button: 03-button.md
    - Temperature: 03-temperature.md
    - Servo: 04-servo.md
    - LED Strip: 05-led-strip.md
    - Displays: 10-displays.md
    - Character LCD: 10-character-lcd-display.md
  - Sensors
    - Potentiometer: 02-pot.md
    - Ultrasonic Distance: 05-ping.md
  - OLED Displays:
    - Introduction: oled/01-oled-intro.md
    - Setup: oled/02-oled-setup.md
    - Drawing: oled/03-oled-drawing.md
    - OLED SSD1306 I2C: oled/11-oled-ssd1306-i2c.md
    - OLED SSD1306 SPI V1: oled/12-oled-ssd1306-spi-v1.md
    - OLED SSD1306 SPI V2: oled/11-oled-ssd1306-spi.md
    - OLED SH1106 I2C Example: oled/11-oled-sh1106-i2c.md
    - OLED Bounce: oled/10-oled-bounce.md
    - OLED Pot: oled/12-oled-pot.md
    - OLED Ping: oled/11-oled-ping.md
    - OLED Pong: oled/11-pong.md
    - OLED Pixel Draw: oled/13-pixel-draw.md
    - OLED References: oled/40-oled-references.md
  - Sound and Music:
    - Introduction: sound/01-intro.md
    - Playing Tones: sound/02-tones.md
    - Play Mario.md: sound/03-play-mario.md
  - Debugging:
    - Debugging Python: 28-debugging-python.md
    - Debugging I2C: 29a-debugging-i2c.md
    - Debugging SPI: 29-debugging-spi.md
    - Ampy: 27-ampy.md
    - Content Outliner: 40-gpt-outliner.md
  - Circuit Python:
    - circuit-python/01-intro.md
  - Projects: projects.md
  - Glossary: glossary.md
  - References: references.md
  - Contact: contact.md
  - Colophon: 30-colophon.md
  - Render Test: mermaid-test.md

site_description: 'Resources for teaching Micropython to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'micropython repo'
repo_url: 'https://github.com/CoderDojoTC/micropython'

# CoderDojo Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  custom_dir: 'theme'
  include_sidebar: true
plugins:
  - mermaid2
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences